### ISSUE TITLE
Upgrade assertj dependency to 2.0.0 ( or greater )

### ISSUE THREAD

**Issue by yogurtearl** [square/assertj-android#154]

**Comment by madisp** [comment]
afaik assertj 2.0.0 depends on JDK7, e.g. java.nio.file.Path - https://code.google.com/p/android/issues/detail?id=161270

**Comment by JakeWharton** [comment]
I was the one who requested Path overloads in AssertJ, funny enough!

In general, the method-overload-all-the-things approach of AssertJ (and FEST before it) is far from ideal and it's my least favorite thing about the library. We've been playing with other ways but the expressiveness (or lack thereof) of Java severely limits us.

Closing for now since there's no way to upgrade.
